### ISSUE TITLE
Some problem

### ISSUE THREAD

**Issue by rebelholic** [djett41/ionic-filter-bar#12]
I already tested your plugin and really cool but got some problem like below:
- Why Nav- bar cannot hide after click search icon and cannot doing vertical transition like my screenshot below:
  ![ionicbar](https://cloud.githubusercontent.com/assets/6254876/8378870/8cbf9548-1c46-11e5-9069-51a5bd4df322.jpg)
  Its my template HTML:
  
  ```
  <ion-view cache-view="false" view-title="Quotation List">
   <ion-nav-buttons side="secondary">
  <button class="button-icon icon ion-ios-search assertive" ng-click="showFilterBar()">
   </button>
  </ion-nav-buttons>
   <ion-content padding="true"> 
     <div class="list">
         <button class="button button-block button-assertive" ng-click="showDetails()">
     <b>Create New Item</b>
          </button>
            </div>
        </ion-content>
      </ion-view>
  ```

How I can fix it?
- How I can add more filter Properties not just one single item to show when searching. Example: I want show "price" item instead "name" item?

**Comment by djett41** [comment]
Thanks @rebelholic can you put together a codepen at http://codepen.io/ so i can see what could be causing the issue?

I added your HTML to the demo and it worked just fine even with vertical animation for android.   After looking at your screenshot it's possible that you may have some conflicting sass or css styles that are causing this, perhaps a Z-index defined somewhere?  Can you post your styles/JS/and HTML in a codepen?

As far as the filter properties, are you trying to filter on "price" OR "name" ? or are you tryging to filter on "price" AND  "name"?  If you are trying to filter on price OR name, then you want to remove the filterProperties option all together from your .show(options) call.  If you re trying to filter on price AND name, then add them in an array for example, filterProperties: ['price', 'name']

**Comment by rebelholic** [comment]
@djett41 Sorry I can't use codepen.io to reproduce my problem because still unfamiliar but you can download my example code [on this link](https://github.com/rebelholic/Ionic-Filter-Bar-Bug/) to reproduce my problem just with "Ionic Serve" on cmd. 
I am using latest version Ionic 1.00

**Comment by djett41** [comment]
I see the issue @rebelholic .

You need to import the ionic-filter-bar.css (or .min file) in your index.html.  Right now you have the ionic css imported, but the ionic-filter-bar css needs to be imported after the ionic.css.

That fixed the issue

**Comment by rebelholic** [comment]
@djett41 Thanks I forgot to add this but I've got another issue like my search result giving "no result" message if we added more than one item to filter Properties like ['name','text'] please check my [updated repo](https://github.com/rebelholic/Ionic-Filter-Bar-Bug/) to reproduce this bug

**Comment by djett41** [comment]
@rebelholic are you trying to do an AND search or an OR search?  

Only use filterProperties if you want the search to check for the search text in ALL properties..

For example,
if you have an object such as the following

```
{
    name: 'rebel',
    text: 'I love ionic'
}
```

if you were to supply filterProperties: ['name', 'text'] and your search input was 'rebel', you would get no results.  This is because the angular filter would check for the text on ALL properties.

If you are trying to search whether or not name OR text has the search text, then remove the filterProperties all together from your show() call.

**Comment by rebelholic** [comment]
@djett41 Thanks for explanation. So AND search have same method with OR search?

**Comment by djett41** [comment]
the filterProperties option in ionic-filter-bar is just for the AND search.  If you want an OR search, then dont use filterProperties

**Comment by rebelholic** [comment]
@djett41 How I can change colour "cancel" text to assertive?

**Comment by djett41** [comment]
you will need to override the sass or css for that button.  the css class for the button is .filter-bar-cancel so you should be able to use that to override the color if you need to in sass or css.

I am going to close this issue since we figured out the issue you were having.  thanks again!

**Comment by rebelholic** [comment]
No problem. Thanks a lot for your help
