### ISSUE TITLE
Filter bar takes up the whole page width when sidemenu is visible

### ISSUE THREAD

**Issue by jayagl** [djett41/ionic-filter-bar#14]
When using ion-side-menu on a tablet and the side menu is visible using 'expose-aside-when' property, the filter bar takes up the whole width of the display instead of just the nav-bar. 

![before](https://cloud.githubusercontent.com/assets/6834917/8588495/9383b276-264e-11e5-975e-bdb3d710e230.png)
![after](https://cloud.githubusercontent.com/assets/6834917/8588499/97e9402e-264e-11e5-8831-a31d53d493a1.png)

**Comment by djett41** [comment]
Thanks @jayagl .  Yeah I have never tested this on tablet layout :-/ 

Is this a slide out side menu?  Or a static side menu??

For slide in/out side menus, I would imagine that the search icon should be disabled if the side menu is slid out, and only when the side menu is in..

However for layouts that use a static side menu then perhaps you could override the width on the ionic-filter-bar container to be the same width as the ionic sass variable for the detail pane.

What are your thoughts?

**Comment by djett41** [comment]
@jayagl I added a container property that you can use to fix this issue.  As the README now shows, set container to '.menu-content' which will make sure the filter bar is only appended to the content section of your ionic side menu!

Thanks again!

**Comment by jayagl** [comment]
Thanks @djett41! Nice solution. It works like a charm :)

**Comment by djett41** [comment]
no prob @jayagl thanks for contributing!
