### ISSUE TITLE
The Keyboard + The bar disappear instantly when a button to activate the filter bar

### ISSUE THREAD

**Issue by olasfar** [djett41/ionic-filter-bar#15]
Hi guys,

I'm facing some issues recently with this module on a real device (Iphone ios 8), when I click on the button to activate the filter bar, the bar + the keyboard appear and disappear instantly.

Any idea what can be the issue ?

Thx in advance?

**Comment by djett41** [comment]
Thanks @olasfar do you have any code or directives that may be blurring inputs or calling blur() ?

**Comment by olasfar** [comment]
Thanks @djett41 for your reactivity :) Nope, I'm not blurring, it's a random bug (kind of race condition), sometimes it works, sometimes it doesn't.. I just tried on my iphone and now it works witch is weird.

**Comment by djett41** [comment]
Interesting!  Any way you can post the code in a separate github project or on codepen?  It would be alot easier for me to see what may be conflicting with it.  Thanks!

**Comment by olasfar** [comment]
I think the issue comes with ionic#v1.0.1, I'll keep you updated.

**Comment by djett41** [comment]
Great thanks!  I'll look at this soon as well

**Comment by djett41** [comment]
@olasfar are you still seeing an issue?  Or can this be closed?

**Comment by olasfar** [comment]
@djett41 I'm still seeing it, it happens only on a real device (I'm using Iphone 5), I should click 3 to 4 times on the button to see the filter bar, otherwise I don't have any JS error on console or on my Sentry report. Please advice. Any ionic option that can cause this ?
FYI I'm using ionic#1.0.0 & ionic-filter-bar#v1.0.3

**Comment by djett41** [comment]
Any way you can post the code for your HTML and controller? Also do you have any keyboard settings in your config.xml?

**Comment by djett41** [comment]
I'm going to go ahead and close this, but if you can provide a codepen or github repo I can replicate the issue on then I'll be happy to reopen and take a look.
