### ISSUE TITLE
Miss : provide a way to close the search bar

### ISSUE THREAD

**Issue by julestruong** [djett41/ionic-filter-bar#17]
I may have missed something but in my case i clearly need to close the search-bar anytime i want.

**Comment by djett41** [comment]
Thanks @julestruong .  Are you speaking of closing it via code programmatically?  Or functionally on device?

On device for ios, you can click the cancel button, or click/swipe the backdrop.  On android you click the back button.

In your controller code, when you call  $ionicFilterBar.show(options), you can assign the result to variable, which is a function to cancel.  See filterBarInstance in the demo app.js controller for an idea.. There you can see when a pull to refresh happens, the controller will cancel the filter bar programmatically if theres a references.

**Comment by julestruong** [comment]
I meant programmatically speaking and didnt know about the cancel returned function. That's great !
