### ISSUE TITLE
[String] filterProperties - Multiple properties

### ISSUE THREAD

**Issue by wardleinc** [djett41/ionic-filter-bar#20]
Hi there,

I'm not sure if this is included in the release but is it possible to search through multiple properties, whereby the 'search string' can match one Filter Property out of an array of multiple Filter Properties and display the results, rather than the 'search string' having to match all filter properties.

Thanks

Edit: My apologies... I found the answer in a closed issue which is to remove filterProperties. Thanks

**Comment by djett41** [comment]
No prob!!!
