### ISSUE TITLE
How to set my custom bar style?

### ISSUE THREAD

**Issue by EricDosReis** [djett41/ionic-filter-bar#22]
Hey, thanks for build this very useful component! Now I need your help.

I have this code:

``` html
<ion-nav-bar class="bar-custom">
    <ion-nav-title>{{ viewTitle }}</ion-nav-title>

    <ion-nav-buttons data-side="right">
        <a class="button button-clear button-icon ion-plus"
            ui-sref="cliente.insert">
        </a>
        <button class="button button-clear button-icon ion-android-search"
            ng-click="showFilterBar()">
        </button>
    </ion-nav-buttons>
</ion-nav-bar>
```

And I want to set my own bar style.

**Comment by djett41** [comment]
@EricDosReis check out the docs.  You need to either 
- Import the scss file if your using SASS like the demo.
- Or if not using SASS, import the CSS file in your index.html and override the styles like you would any other CSS

**Comment by EricDosReis** [comment]
Yes, works fine.

Thanks!
