### ISSUE TITLE
Issue with .transition('horizontal')

### ISSUE THREAD

**Issue by NBAMj** [djett41/ionic-filter-bar#3]
I must say, I really like your component so far.
The ability to customize so many things is very nice and I am stilling testing the component.

The problem I faced is when using the transition 'horizontal' with $ionicFilterBarConfigProvider.
Take a look at the img:
![ion-search-filter-issue](https://cloud.githubusercontent.com/assets/3479105/7830343/617775dc-045d-11e5-8f8e-75aaf5b320cf.gif)

**Comment by djett41** [comment]
thanks @NBAMj so the issue seems to be for the IOS layout and horizontal transition correct?

I can take a look at it today or tomorrow thanks!

**Comment by djett41** [comment]
I released a new version 1.0.1 with the fix.  Thanks! @NBAMj
