### ISSUE TITLE
Filtering

### ISSUE THREAD

**Issue by kumaro** [djett41/ionic-filter-bar#33]
Thanks for the awesome plugin. I have a question about filtering. 
Current filter matches All properties defined in filterProperties. Any idea how to set up for any property match?

**Comment by kumaro** [comment]
Found my answer in Issue:12  
Or works by default . filter Properties is for And. Thanks again!

**Comment by djett41** [comment]
cool no prob!  If you need OR functionality, you can use the expression function option.  See docs/tests for more info!  Thanks again!

**Comment by djett41** [comment]
oops just reread and you were looking for ALL which as you pointed out is the default (no filter properties) Thanks again!
