### ISSUE TITLE
How to Filter Items Properly

### ISSUE THREAD

**Issue by verdi327** [djett41/ionic-filter-bar#36]
Do I have to structure my objects in any particular way for the filtering to work?  I have an array of players.  Each player looks like:

`{first_name: "john", last_name: "smith"}`

My code looks like...

```
$scope.showFilterBar = function () {
      filterBarInstance = $ionicFilterBar.show({
        items: $scope.players,
        filterProperties: ["first_name", "last_name"],
        update: function (filteredItems, filterText) {
          $scope.players = filteredItems;
          if (filterText) {
            console.log(filterText);
          }
        }
      });
    };
```

But, I am getting no results back when I start typing a name that exists in my list.  Any tips?

**Comment by djett41** [comment]
@verdi327 Take a look at the docs for filterProperties in the README.  filterProperties creates an AND expression.  If you need to filter on first_name OR last_name, then don't include filterProperties.

**Comment by verdi327** [comment]
Ah, that makes sense now.  I got it working.
