### ISSUE TITLE
There is a bug when using ionic filter bar inside a modal.

### ISSUE THREAD

**Issue by EricDosReis** [djett41/ionic-filter-bar#49]
Filter bar inside a modal doesn't close automatically when I click out or in cancel button.

**Comment by Murthy582** [comment]
Agree with @EricDosReis, though filter bar appearing on the screen, not able to interact with it like tapping on text box or cancel button. My modal has a close button on its header, I'm able to close the modal using that button though the filter bar overriden the modal header bar.

**Comment by djett41** [comment]
Do you have a codepen or demo of this?  I'm not must not be visualizing your scenario correctly, but I'm using it in a modal and the filter bar covers my header which has my close button.  So I have to close the filter bar before I can close the modal.

Are you guys seeing different?  Thanks

**Comment by EricDosReis** [comment]
I captured a demo of my app. See bellow

Filter bar in a simple view close normaly:

![works-fine](https://cloud.githubusercontent.com/assets/6003424/10437375/f49bc5ae-7102-11e5-95a4-5ec321229cad.gif)

and filter bar in a modal doesn't close:

![broke](https://cloud.githubusercontent.com/assets/6003424/10437391/1731c866-7103-11e5-8446-673039a11873.gif)

**Comment by EricDosReis** [comment]
Yes! Resolved!

When the Ionic modal is open the pointer events are none, disabling any action in the body element

``` css
.modal-open {
    pointer-events: none;
}
```

In my custom css file I put this rule

``` css
.filter-bar-open.modal-open { 
    pointer-events: auto 
}
```

and works fine :)

**Comment by i3i2ain** [comment]
@EricDosReis awesome, your css fix saved me probably almost a day of struggling with that issue :)

**Comment by abdulwahid24** [comment]
@EricDosReis Thanks a ton.
