### ISSUE TITLE
Ionic header bar is pushed down in android

### ISSUE THREAD

**Issue by kianliang-iium** [djett41/ionic-filter-bar#52]
Thank you for the great plugin. However I have problem with android header bar being pushed down when input appears. By the way, it works perfectly in iOS.

<img width="377" alt="ios" src="https://cloud.githubusercontent.com/assets/13483690/10361585/a3e4f3a8-6ddb-11e5-906c-970ea7d0027d.png">
Works perfectly in iOS! The header is under the search bar.

<img width="379" alt="android" src="https://cloud.githubusercontent.com/assets/13483690/10361597/bf68f818-6ddb-11e5-9178-bc2497a9fe2d.png">
Header is pushed down. The header is created using ion-header-bar in a ion-side-menu.

**Comment by djett41** [comment]
Do you have a codepen of your HTML setup?  If so I can take a look.  Thanks!

**Comment by kianliang-iium** [comment]
I have managed to solved it by strictly using ion-header-bar in the ion-side-menu. This problem is caused by mixing ion-nav-view and ion-header-bar within the ion-side-menu

**Comment by djett41** [comment]
Nice sounds good!!!! Glad you could figure it out
