### ISSUE TITLE
$ionicfilterBarConfigProvider not available

### ISSUE THREAD

**Issue by bbisinger** [djett41/ionic-filter-bar#6]
Love the directive, but it appears the documentation doesn't match the code. There is no "$ionicfilterBarConfigProvider" available for injection. There is a '$ionicfilterBarConfig', but it doesn't allow for easy theme switching as the documents suggest. Also, the default theme is set to 'positive', not 'light' or 'stable' as needed.

**Comment by djett41** [comment]
@captainjim1 thanks and nice catch!! I modified the config to be consistent with the docs (light theme for android, stable for ios and others)

As far as changing the theme, I also added a NOTE to the docs reminding that the ion-nav-bar theme class must be consistent with the ionic-filter-bar theme.  So if you look in the demo at index.html, you will see ion-nav-bar has a bar-positive css class.  This must be consistent with the ionic-filter-bar theme and must also change if the filter bar theme changes.

Also make sure you injecting the ionicfilterBarConfigProvider in the config section of your module.  Take a look at the demo/app.js so you will see where that's injected.  The demo now changes the theme to positive which shows that the theme switching is working as expected.  

Let me know if you have any questions and thanks again!!

**Comment by djett41** [comment]
I also forgot to mention, I just published version 1.0.2 with the changes mentioned above so download the latest when you get a chance thanks!

**Comment by djett41** [comment]
@captainjim1 I actually went a different route now and just released an even newer version 1.0.3.

Now the theme is inherited by the ion-nav-bar theme/color options.  So if you look at the demo, the ion-nav-bar has a "bar-positive" class.  The filter bar will now stay consistent with ion-nav-bar and automatically have a "filter-bar-positive" class as a result, maintaining the positive theme..

You can still override the filter bar theme by using the ionicfilterBarConfigProvider, but the defaults are now consistent with the ion-nav-bar.  ion-nav-bar defaults to the light theme, so ionic-filter-bar will also default to the light theme for all platforms

**Comment by bbisinger** [comment]
Perfect! Thanks for the quick turn around!

**Comment by djett41** [comment]
no prob thanks for bringing it to my attention!
