### ISSUE TITLE
Filter bar covers modal header

### ISSUE THREAD

**Issue by rashnk** [djett41/ionic-filter-bar#60]
i want to open a modal when an item is clicked from the filtered list, it works fine, but the search bar is displayed on top of the modal' header, i cant see the buttons on modal view, is there any way to show modal header to the front so the search bar will be coverd

**Comment by kiranj91** [comment]
I have the same problem. Did u find the solution??

**Comment by rashnk** [comment]
set z-index for the filter bar css
